# Generated by Django 4.2.4 on 2023-08-17 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='price',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('other', 'Other'), ('dance', 'Dance Music'), ('country', 'Country Music'), ('rnb', 'R&B Music'), ('jazz', 'Jazz Music'), ('pop', 'Pop Music'), ('rock', 'Rock Music'), ('hiphop', 'Hip Hop Music')], max_length=30),
        ),
    ]
