# Generated by Django 4.2.4 on 2023-08-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_album_description_album_image_album_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('dance', 'Dance Music'), ('rnb', 'R&B Music'), ('hiphop', 'Hip Hop Music'), ('other', 'Other'), ('country', 'Country Music'), ('jazz', 'Jazz Music'), ('pop', 'Pop Music'), ('rock', 'Rock Music')], max_length=30),
        ),
    ]
