# Generated by Django 4.2.4 on 2023-08-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_alter_album_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('country', 'Country Music'), ('pop', 'Pop Music'), ('rock', 'Rock Music'), ('other', 'Other'), ('dance', 'Dance Music'), ('hiphop', 'Hip Hop Music'), ('rnb', 'R&B Music'), ('jazz', 'Jazz Music')], max_length=30),
        ),
    ]
