# Generated by Django 4.2.4 on 2023-08-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_alter_album_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('other', 'Other'), ('jazz', 'Jazz Music'), ('rnb', 'R&B Music'), ('rock', 'Rock Music'), ('hiphop', 'Hip Hop Music'), ('Dance Music', 'Dance Music'), ('country', 'Country Music'), ('pop', 'Pop Music')], max_length=30),
        ),
    ]
