# Generated by Django 4.2.4 on 2023-08-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0005_alter_album_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('Jazz Music', 'Jazz Music'), ('Country Music', 'Country Music'), ('Other', 'Other'), ('Pop Music', 'Pop Music'), ('Hip Hop Music', 'Hip Hop Music'), ('R&B Music', 'R&B Music'), ('Rock Music', 'Rock Music'), ('Dance Music', 'Dance Music')], max_length=30),
        ),
    ]
