# Generated by Django 4.2.4 on 2023-08-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0006_alter_album_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('Dance Music', 'Dance Music'), ('Rock Music', 'Rock Music'), ('R&B Music', 'R&B Music'), ('Pop Music', 'Pop Music'), ('Country Music', 'Country Music'), ('Jazz Music', 'Jazz Music'), ('Hip Hop Music', 'Hip Hop Music'), ('Other', 'Other')], max_length=30),
        ),
    ]
