# Generated by Django 4.2.4 on 2023-08-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0007_alter_album_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('Pop Music', 'Pop Music'), ('Other', 'Other'), ('Hip Hop Music', 'Hip Hop Music'), ('Jazz Music', 'Jazz Music'), ('Rock Music', 'Rock Music'), ('Country Music', 'Country Music'), ('R&B Music', 'R&B Music'), ('Dance Music', 'Dance Music')], max_length=30),
        ),
    ]
